# Generated by Django 4.2.7 on 2023-11-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_listing_bathrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
