# Generated by Django 4.2.7 on 2023-11-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_propertycomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PropertyComment",
        ),
    ]
